### ISSUE TITLE
Delete stamp no longer works

### ISSUE THREAD

**Issue by jadrake75** [stamp-web/stamp-web-aurelia#118]
Error in the console

core-framework.js:6 ERROR [event-aggregator] Error: $.fn.modal is not defined; please double check you have included the Bootstrap JavaScript library. See http://getbootstrap.com/javascript/ for more details.
    at Object.p.dialog (http://drake-server.ddns.net:9005/stamp-aurelia/dist/core-ui.js:8:31384)
    at Object.p.confirm (http://drake-server.ddns.net:9005/stamp-aurelia/dist/core-ui.js:8:28941)
    at Array.eval (http://drake-server.ddns.net:9005/stamp-aurelia/dist/stampweb-list.js:3:28648)
    at a.EventAggregator.a.publish (http://drake-server.ddns.net:9005/stamp-aurelia/dist/core-framework.js:7:19677)
    at a.remove (http://drake-server.ddns.net:9005/stamp-aurelia/dist/stampweb-list.js:2:6106)

**Comment by jadrake75** [comment]
This is fixed
